#!/usr/bin/env python3
"""
Generate LaTeX snippet for P1 appendix: per-sequence corpus summary (longtable).
Reads eval.json and writes papers/P1_Contracts/generated_appendix_corpus.tex

Usage:
  python scripts/export_p1_appendix_tex.py [--eval path]
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DEFAULT_EVAL = REPO / "datasets" / "runs" / "contracts_eval" / "eval.json"
DEFAULT_OUT = REPO / "papers" / "P1_Contracts" / "generated_appendix_corpus.tex"


def _tex_escape(s: str) -> str:
    return s.replace("\\", "\\textbackslash{}").replace("_", "\\_")


def main() -> int:
    ap = argparse.ArgumentParser(description="Export P1 appendix LaTeX from eval.json")
    ap.add_argument("--eval", type=Path, default=DEFAULT_EVAL)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()
    if not args.eval.exists():
        print(f"Error: {args.eval} not found.")
        return 1
    data = json.loads(args.eval.read_text(encoding="utf-8"))
    rm = data.get("run_manifest", {})
    sequences = data.get("sequences", [])

    lines = [
        "% Auto-generated by scripts/export_p1_appendix_tex.py — do not edit by hand.",
        "% Regenerate: python scripts/export_p1_appendix_tex.py --eval <path/to/eval.json>",
        "",
        r"\begin{longtable}{p{0.52\linewidth}cc}",
        r"\caption{Per-sequence corpus summary (frozen run).}\label{tab:appendixcorpus}\\",
        r"\toprule",
        r"Sequence & Detection OK & Contract denials \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Sequence & Detection OK & Contract denials \\",
        r"\midrule",
        r"\endhead",
    ]
    for s in sequences:
        seq = _tex_escape(s.get("sequence", ""))
        ok = "yes" if s.get("detection_ok") else "no"
        den = s.get("denials", 0)
        lines.append(f"{seq} & {ok} & {den} \\\\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{longtable}")
    lines.append("")
    sv = _tex_escape(str(rm.get("script_version", "")))
    fp = _tex_escape(str(rm.get("corpus_fingerprint", "")))
    cnt = rm.get("corpus_sequence_count", len(sequences))
    lines.append(
        r"\paragraph{Run manifest (reproducibility).} "
        rf"Script version \texttt{{{sv}}}; corpus fingerprint \texttt{{{fp}}}; sequence count {cnt}."
    )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
