#!/usr/bin/env python3
"""
P4 MAESTRO baseline: Centralized vs Blackboard on same scenario and seed band.
Output: bench/maestro/baseline_results.md and baseline_summary.json.
Usage: PYTHONPATH=impl/src python scripts/maestro_baselines.py [--scenario ID]
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "impl" / "src"))
if "LABTRUST_KERNEL_DIR" not in os.environ:
    os.environ["LABTRUST_KERNEL_DIR"] = str(REPO_ROOT / "kernel")


def main() -> int:
    ap = argparse.ArgumentParser(
        description="P4: Centralized vs Blackboard baseline"
    )
    ap.add_argument(
        "--scenario",
        type=str,
        default="toy_lab_v0",
        help="Scenario id",
    )
    ap.add_argument(
        "--seeds",
        type=int,
        default=20,
        help="Number of seeds (1..N); default 20 for publishable; use 30 for sensitivity; CI may override with fewer",
    )
    args = ap.parse_args()

    from labtrust_portfolio.adapters.centralized import CentralizedAdapter
    from labtrust_portfolio.adapters.blackboard import BlackboardAdapter
    from labtrust_portfolio.adapters.retry_heavy import RetryHeavyAdapter

    adapters = [
        ("Centralized", CentralizedAdapter()),
        ("Blackboard", BlackboardAdapter()),
        ("RetryHeavy", RetryHeavyAdapter()),
    ]
    fault_params = {"drop_completion_prob": 0.0, "delay_p95_ms": 50.0}
    rows = []

    for name, adapter in adapters:
        for seed in range(1, args.seeds + 1):
            with tempfile.TemporaryDirectory() as td:
                out_dir = Path(td)
                res = adapter.run(args.scenario, out_dir, seed=seed, **fault_params)
                report = res.maestro_report
                m = report["metrics"]
                rows.append(
                    {
                        "adapter": name,
                        "seed": seed,
                        "tasks_completed": m["tasks_completed"],
                        "coordination_messages": m["coordination_messages"],
                        "p95_latency_ms": round(m["task_latency_ms_p95"], 2),
                    }
                )

    out_dir = REPO_ROOT / "bench" / "maestro"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "baseline_results.md"
    summary_path = out_dir / "baseline_summary.json"
    summary_path.write_text(
        json.dumps(
            {"scenario": args.scenario, "seeds": args.seeds, "rows": rows},
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    lines = [
        "# MAESTRO baseline comparison (P4)",
        "",
        f"Scenario: `{args.scenario}`. Seeds 1..{args.seeds}. "
        "Fault params: drop_completion_prob=0, delay_p95_ms=50.",
        "",
        "| Adapter | Seed | tasks_completed | coordination_messages | "
        "p95_latency_ms |",
        "|---------|------|-----------------|------------------------|----------------|",
    ]
    for r in rows:
        line = (
            f"| {r['adapter']} | {r['seed']} | {r['tasks_completed']} | "
            f"{r['coordination_messages']} | {r['p95_latency_ms']} |"
        )
        lines.append(line)
    lines.extend([
        "",
        "Reference adapter comparison (same pipeline, different defaults).",
        "",
        "Generated by `scripts/maestro_baselines.py`.",
    ])
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(out_path.read_text(encoding="utf-8"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
