#!/usr/bin/env python3
"""
Plot P5 Scaling: MAE by held-out scenario from heldout_results.json.
Output: docs/figures/p5_scaling_mae.png. Autogenerated from release; required for Draft.
Usage: PYTHONPATH=impl/src python scripts/plot_scaling_mae.py [--results path] [--out path]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DEFAULT_RESULTS = REPO / "datasets" / "runs" / "scaling_eval" / "heldout_results.json"
DEFAULT_OUT = REPO / "docs" / "figures" / "p5_scaling_mae.png"


def main() -> int:
    ap = argparse.ArgumentParser(description="Plot P5 scaling MAE by held-out scenario")
    ap.add_argument("--results", type=Path, default=DEFAULT_RESULTS, help="heldout_results.json path")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT, help="Output PNG path")
    args = ap.parse_args()

    if not args.results.exists():
        print(f"Error: {args.results} not found. Run scripts/scaling_heldout_eval.py first.")
        return 1

    data = json.loads(args.results.read_text(encoding="utf-8"))
    results = data.get("held_out_results", [])
    if not results:
        print("Error: no held_out_results in file.")
        return 1

    def _float_or_zero(v): return float(v) if v is not None else 0.0
    scenarios = [
        r.get("holdout_label") or r.get("held_out_scenario", "?") for r in results
    ]
    baseline_mae = [_float_or_zero(r.get("baseline_mae")) for r in results]
    feat_mae = [_float_or_zero(r.get("feat_baseline_mae")) for r in results]
    reg_mae = [_float_or_zero(r.get("regression_mae")) for r in results]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import numpy as np
        x = np.arange(len(scenarios))
        w = 0.25
        fig, ax = plt.subplots()
        ax.bar(x - w, baseline_mae, w, label="Global mean")
        ax.bar(x, feat_mae, w, label="Per-scenario/feat")
        ax.bar(x + w, reg_mae, w, label="Regression")
        ax.set_xticks(x)
        ax.set_xticklabels(scenarios, rotation=20)
        ax.set_ylabel("MAE (tasks_completed)")
        ax.set_title("P5 Scaling: MAE by held-out scenario")
        ax.legend()
        plt.tight_layout()
        plt.savefig(args.out, dpi=150)
        plt.close()
        print(f"Wrote {args.out}")
    except ImportError:
        out_data = {"scenarios": scenarios, "baseline_mae": baseline_mae, "feat_baseline_mae": feat_mae, "regression_mae": reg_mae}
        json_path = args.out.with_suffix(".json")
        json_path.write_text(json.dumps(out_data, indent=2) + "\n", encoding="utf-8")
        print(f"matplotlib not installed. Wrote {json_path} for external plotting.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
