#!/usr/bin/env python3
"""
Plot P2 REP-CPS: tasks_completed by policy (or delay_sweep) from rep_cps_eval summary.json.
Output: docs/figures/p2_rep_cps_tasks.png. Autogenerated from release; required for Draft.
Usage: PYTHONPATH=impl/src python scripts/plot_rep_cps_summary.py [--summary path] [--out path]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DEFAULT_SUMMARY = REPO / "datasets" / "runs" / "rep_cps_eval" / "summary.json"
DEFAULT_OUT = REPO / "docs" / "figures" / "p2_rep_cps_tasks.png"


def main() -> int:
    ap = argparse.ArgumentParser(description="Plot P2 REP-CPS tasks_completed by policy")
    ap.add_argument("--summary", type=Path, default=DEFAULT_SUMMARY, help="summary.json path")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT, help="Output PNG path")
    args = ap.parse_args()

    if not args.summary.exists():
        print(f"Error: {args.summary} not found. Run scripts/rep_cps_eval.py first.")
        return 1

    data = json.loads(args.summary.read_text(encoding="utf-8"))
    policies = []
    means = []
    stdevs = []
    for key, label in [
        ("rep_cps_tasks_completed_mean", "REP-CPS"),
        ("centralized_tasks_completed_mean", "Centralized"),
        ("rep_cps_naive_tasks_completed_mean", "Naive-in-loop"),
        ("rep_cps_unsecured_tasks_completed_mean", "Unsecured"),
    ]:
        m = data.get(key)
        if m is not None:
            policies.append(label)
            means.append(float(m))
            stdev = data.get(key.replace("_mean", "_stdev"), 0) or 0
            stdevs.append(float(stdev))

    if not policies:
        delay_sweep = data.get("delay_sweep", [])
        if delay_sweep:
            policies = [f"d={r.get('delay_fault_prob', '?')}" for r in delay_sweep]
            means = [float(r.get("rep_cps_tasks_mean", r.get("rep_cps_tasks_completed_mean", 0))) for r in delay_sweep]
            stdevs = [float(r.get("rep_cps_tasks_stdev", 0)) for r in delay_sweep]
        else:
            print("Error: no adapter or delay_sweep data in summary.")
            return 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        fig, ax = plt.subplots()
        x = range(len(policies))
        ax.bar(x, means, yerr=stdevs if any(s > 0 for s in stdevs) else None, capsize=3)
        ax.set_xticks(x)
        ax.set_xticklabels(policies, rotation=15)
        ax.set_ylabel("tasks_completed (mean)")
        ax.set_title("P2 REP-CPS: tasks_completed by policy")
        plt.tight_layout()
        plt.savefig(args.out, dpi=150)
        plt.close()
        print(f"Wrote {args.out}")
    except ImportError:
        out_data = {"policies": policies, "means": means, "stdevs": stdevs}
        json_path = args.out.with_suffix(".json")
        json_path.write_text(json.dumps(out_data, indent=2) + "\n", encoding="utf-8")
        print(f"matplotlib not installed. Wrote {json_path} for external plotting.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
