#!/usr/bin/env python3
"""
Plot P6 LLM: adapter latency (p95 or wall_sec) by scenario from adapter_latency.json.
Output: docs/figures/p6_adapter_latency.png. Autogenerated from release; required for Draft.
Usage: PYTHONPATH=impl/src python scripts/plot_llm_adapter_latency.py [--latency path] [--out path]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DEFAULT_LATENCY = REPO / "datasets" / "runs" / "llm_eval" / "adapter_latency.json"
DEFAULT_OUT = REPO / "docs" / "figures" / "p6_adapter_latency.png"


def main() -> int:
    ap = argparse.ArgumentParser(description="Plot P6 adapter latency by scenario")
    ap.add_argument("--latency", type=Path, default=DEFAULT_LATENCY, help="adapter_latency.json path")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT, help="Output PNG path")
    args = ap.parse_args()

    if not args.latency.exists():
        print(f"Error: {args.latency} not found. Run scripts/llm_redteam_eval.py --run-adapter first.")
        return 1

    data = json.loads(args.latency.read_text(encoding="utf-8"))
    runs = data.get("runs", [])
    if not runs:
        tail = data.get("tail_latency_p95_mean_ms")
        if tail is not None:
            runs = [{"scenario_id": data.get("scenarios", ["default"])[0], "task_latency_ms_p95": tail}]
    if not runs:
        print("Error: no runs or tail_latency in adapter_latency.json.")
        return 1

    by_scenario = {}
    for r in runs:
        sid = r.get("scenario_id", "default")
        p95 = r.get("task_latency_ms_p95") or r.get("wall_sec")
        if p95 is not None:
            by_scenario.setdefault(sid, []).append(float(p95))
    scenarios = list(by_scenario.keys())
    values = [by_scenario[sid] for sid in scenarios]
    means = [sum(v) / len(v) for v in values]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        fig, ax = plt.subplots()
        ax.bar(range(len(scenarios)), means)
        ax.set_xticks(range(len(scenarios)))
        ax.set_xticklabels(scenarios, rotation=20)
        ax.set_ylabel("Latency (p95 ms or wall s)")
        ax.set_title("P6 LLM adapter latency by scenario")
        plt.tight_layout()
        plt.savefig(args.out, dpi=150)
        plt.close()
        print(f"Wrote {args.out}")
    except ImportError:
        out_data = {"scenarios": scenarios, "means": means, "per_run": [by_scenario[s] for s in scenarios]}
        json_path = args.out.with_suffix(".json")
        json_path.write_text(json.dumps(out_data, indent=2) + "\n", encoding="utf-8")
        print(f"matplotlib not installed. Wrote {json_path} for external plotting.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
