#!/usr/bin/env python3
"""
Plot P8 Meta: tasks_completed or collapse rate vs drop_prob from collapse_sweep.json.
Output: docs/figures/p8_meta_collapse.png. Autogenerated from release; required for Draft.
Usage: PYTHONPATH=impl/src python scripts/plot_meta_collapse.py [--sweep path] [--out path]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DEFAULT_SWEEP = REPO / "datasets" / "runs" / "meta_eval" / "collapse_sweep.json"
DEFAULT_OUT = REPO / "docs" / "figures" / "p8_meta_collapse.png"


def main() -> int:
    ap = argparse.ArgumentParser(description="Plot P8 collapse sweep: tasks_completed vs drop_prob")
    ap.add_argument("--sweep", type=Path, default=DEFAULT_SWEEP, help="collapse_sweep.json path")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT, help="Output PNG path")
    args = ap.parse_args()

    if not args.sweep.exists():
        print(f"Error: {args.sweep} not found. Run scripts/meta_collapse_sweep.py first.")
        return 1

    data = json.loads(args.sweep.read_text(encoding="utf-8"))
    per_run = data.get("per_run", [])
    if not per_run:
        print("Error: no per_run in collapse_sweep.json.")
        return 1

    by_drop = {}
    for r in per_run:
        d = r.get("drop_prob")
        if d is not None:
            by_drop.setdefault(d, []).append(r.get("tasks_completed", 0))
    drop_probs = sorted(by_drop.keys())
    means = [sum(by_drop[d]) / len(by_drop[d]) for d in drop_probs]
    collapse_rates = []
    for d in drop_probs:
        runs_d = [r for r in per_run if r.get("drop_prob") == d]
        n = len(runs_d)
        collapsed_n = sum(1 for r in runs_d if r.get("collapsed"))
        collapse_rates.append(collapsed_n / n if n else 0)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        fig, ax1 = plt.subplots()
        ax1.plot(drop_probs, means, "o-", color="C0")
        ax1.set_xlabel("drop_completion_prob")
        ax1.set_ylabel("tasks_completed (mean)", color="C0")
        ax1.tick_params(axis="y", labelcolor="C0")
        ax2 = ax1.twinx()
        ax2.plot(drop_probs, collapse_rates, "s--", color="C1")
        ax2.set_ylabel("collapse rate", color="C1")
        ax2.tick_params(axis="y", labelcolor="C1")
        ax1.set_title("P8 Meta: tasks_completed and collapse rate vs drop_prob")
        plt.tight_layout()
        plt.savefig(args.out, dpi=150)
        plt.close()
        print(f"Wrote {args.out}")
    except ImportError:
        out_data = {"drop_probs": drop_probs, "tasks_completed_mean": means, "collapse_rate": collapse_rates}
        json_path = args.out.with_suffix(".json")
        json_path.write_text(json.dumps(out_data, indent=2) + "\n", encoding="utf-8")
        print(f"matplotlib not installed. Wrote {json_path} for external plotting.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
