"""Stable failure reason codes for P7 assurance / governance review (negative controls)."""

# Pack / mapping structure
PACK_SCHEMA_INVALID = "PACK_SCHEMA_INVALID"
CONTROL_REFERENCE_MISSING = "CONTROL_REFERENCE_MISSING"
CONTROL_EVIDENCE_TYPES_MISSING = "CONTROL_EVIDENCE_TYPES_MISSING"
PROFILE_PONR_UNCOVERED = "PROFILE_PONR_UNCOVERED"
EVIDENCE_MAP_INCONSISTENT = "EVIDENCE_MAP_INCONSISTENT"

# Artifacts
TRACE_MISSING = "TRACE_MISSING"
BUNDLE_MISSING = "BUNDLE_MISSING"
MAESTRO_MISSING = "MAESTRO_MISSING"
RELEASE_MANIFEST_MISSING = "RELEASE_MANIFEST_MISSING"
TRACE_SCHEMA_INVALID = "TRACE_SCHEMA_INVALID"
BUNDLE_SCHEMA_INVALID = "BUNDLE_SCHEMA_INVALID"

# Scenario / PONR / provenance
PONR_MISSING = "PONR_MISSING"
SCENARIO_PACK_MISMATCH = "SCENARIO_PACK_MISMATCH"
PROVENANCE_MISMATCH = "PROVENANCE_MISMATCH"
INCOMPLETE_EVIDENCE = "INCOMPLETE_EVIDENCE"

UNKNOWN_REVIEW_FAILURE = "UNKNOWN_REVIEW_FAILURE"

ALL_CODES = frozenset(
    {
        PACK_SCHEMA_INVALID,
        CONTROL_REFERENCE_MISSING,
        CONTROL_EVIDENCE_TYPES_MISSING,
        PROFILE_PONR_UNCOVERED,
        EVIDENCE_MAP_INCONSISTENT,
        TRACE_MISSING,
        BUNDLE_MISSING,
        MAESTRO_MISSING,
        RELEASE_MANIFEST_MISSING,
        TRACE_SCHEMA_INVALID,
        BUNDLE_SCHEMA_INVALID,
        PONR_MISSING,
        SCENARIO_PACK_MISMATCH,
        PROVENANCE_MISMATCH,
        INCOMPLETE_EVIDENCE,
        UNKNOWN_REVIEW_FAILURE,
    }
)
